name: Run Stryker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  stryker-test:
    permissions:
      checks: write # for coverallsapp/github-action to create new checks
      contents: read # for actions/checkout to fetch code
    name: Run Stryker
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    env:
      TEST_ENV: ${{ matrix.test_env || 'production' }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: cp install/package.json package.json
      - run: cp install/stryker.config.json stryker.config.json

      - name: Install & Build
        run: |
          npm install
          ./nodebb setup

      - name: Run Stryker Test
        run: npm run mutation
